### ISSUE TITLE
more info on the xml protocol

### ISSUE THREAD

**Issue by ahmet8282** [natevoci/ae200#1]
Hello @natevoci ,

Thank you for putting publishing this package. I will probably need to have this integration. I am curious where did you learn about the xml protocal that ae-200 uses? Do you have any documentation? Which settings of the air conditioner can change?

**Comment by natevoci** [comment]
Hi @ahmettahasakar. I don't have any documentation. I just got the xml from chrome devtools by performing the actions I wanted to implement in the ae200 web interface.

**Comment by ahmet8282** [comment]
Nice and cool. That way i can capture and replay any commands i need as well.
